### ISSUE TITLE
ERROR: Enter a valid date/time

### ISSUE THREAD

**Issue by BadCo-NZ** [babybuddy/babybuddy#337]
Hi,

I woke up this morning to BabyBuddy being down, checked github and noticed there was an issue with the latest release, so while the fix was being worked on I decided to move BabyBuddy from being a docker run command to a docker-compose file.

docker-compose file:

```
version: "2.1"
services:
  app:
    image: lscr.io/linuxserver/babybuddy:amd64-latest
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - config:/config
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.10.11.211
    dns:
      - 10.10.11.1
      
networks:
  default:
    external:
      name: public
      
volumes:
  config:
```

I have now pulled the latest image 1.9.1-ls16, and I am having an issue with date/time when adding entries. See example below.

![Screenshot_20211115_135754](https://user-images.githubusercontent.com/50016048/141706794-36a57621-64c7-4518-b51b-76309e78a496.png)

I have tried different TZ variables but it doesn't seem to change the outcome.

When I go to a running timer, and say, add it as a sleep timer, the time and date values appear then disappear.

I believe I was running version 1.8, I can roll back to a backup from last night to check.

Anyone have any suggestions?

**Comment by cdubz** [comment]
> When I go to a running timer, and say, add it as a sleep timer, the time and date values appear then disappear.

I actually saw this weird behavior briefly after recent dependency updates and then it went away and I couldn’t reproduce it again. Maybe try a hard refresh to clear browser caches?

The invalid date/time thing _may_ also be related to/fixed by that. But if not — what language setting are you using?

**Comment by BadCo-NZ** [comment]
> > When I go to a running timer, and say, add it as a sleep timer, the time and date values appear then disappear.
> 
> I actually saw this weird behavior briefly after recent dependency updates and then it went away and I couldn’t reproduce it again. Maybe try a hard refresh to clear browser caches?
> 
> The invalid date/time thing _may_ also be related to/fixed by that. But if not — what language setting are you using?
> 
> edit: oh I guess from the screenshot it looks pretty clearly to be English (: There are some changes to date format handling in v1.9.1 and that datetime format looks like should be treated as valid. Let me know if a cache clear doesn’t do any good.

Yup, English is correct :)

I tried clearing cache and site data in FireFox and LibreWolf, but it did not change any behavior.

**Comment by BadCo-NZ** [comment]
Rolling back to 1.9.0-ls14 fixes the issue.

Should I make create an issue at linuxserver/docker-babybuddy?

**Comment by cdubz** [comment]
I don’t think so. I bet this has something to do with recent changes to language handling and custom formats (i.e. not an issue with the Docker implementation but with the app itself). I’ll take a look in the next few days.

**Comment by BadCo-NZ** [comment]
No worries. Let me know if you need me to test some more, I can spin up a duplicate container with the latest release.

**Comment by Borlean** [comment]
I'm having the same issue and can't add any sleep or tummy time.  Whats the full link to downgrade to v 1.9.0? 
using lscr.io/linuxserver/babybuddy:1.9.0-ls14 just breaks the container.

**Comment by cdubz** [comment]
Are either of you able to reproduce this issue at http://demo.baby-buddy.net?

**Comment by BadCo-NZ** [comment]
> I'm having the same issue and can't add any sleep or tummy time. Whats the full link to downgrade to v 1.9.0? using lscr.io/linuxserver/babybuddy:1.9.0-ls14 just breaks the container.
> 
> EditL Nevermind, i figured it out.... lscr.io/linuxserver/babybuddy:1.9.0

`lscr.io/linuxserver/babybuddy:v1.9.0-ls14`

worked for me, note the 'v'



> Are any of you able to reproduce this issue at http://demo.baby-buddy.net?

Yes, I get the same error.

Buuut, I went into the user settings, set the timezone to Pacific/Auckland and language to en_GB and now it works.

**Comment by cdubz** [comment]
> Yes, I get the same error.

Interesting! I’m not able to reproduce… can you give me exact steps to try?

**Comment by BadCo-NZ** [comment]
Ok, so I re-pulled the latest image, went into settings and the correct timezone was already selected. Changed language to en_GB. Threw a nappy change in and it worked.

A bit more testing, when I start a timer, then add it as a sleep entry, the date values still disappear, but aslong as I back date the time by 1min before the current time then it will get accepted.

**Comment by Amith211** [comment]
FYI, I couldn't reproduce the invalid date format in Firefox, Chrome nor Edge.
I tried using `UTC` with both `en_US` and `en_GB`, and Pacific/Auckland with both `en_US` and 'en_GB' on http://demo.baby-buddy.net and in docker, which is strange.

I can reproduce your other issue when using the timer to add an entry with `Pacific/Auckland` and `en_GB` set.
It appears as if the date format is not as expected for the date picker, its inserting using `2021-11-16 09:30:00` format, which the picker removes as it is not expecting that format.

Good news! I tested this again and it appears to be fixed with the changes in #335 , but I can't tell if your original issue would be addressed as part of that.

**Comment by cdubz** [comment]
@Amith211 thanks for testing. Sorry I haven't made a review of #335 yet -- it'll probably be a few more days. I did kick off the Heroku PR environment deploy though, so you (and others in this thread) can also test in this public environment with your changes: https://babybuddy-pr-335.herokuapp.com/

**Comment by BadCo-NZ** [comment]
Cheers for the info. If I get a chance today I'll spin up a updated clone and see if that has any issues.

**Comment by meeb** [comment]
Anecdotal confirmation, we also experienced this issue with the "Enter a valid date/time" error for valid dates. Downgrading to v1.9.0-ls14 resolved it for our local install via Docker. Our container timezone is "Australia/Hobart". I can't replicate this on http://demo.baby-buddy.net/ which seems to work properly.

**Comment by cdubz** [comment]
I just pushed some commits related to #346 that may relate to this issue as well. Appreciate if folks who are able to run an instance from `master` can give their issues from this thread a test again. I also hope to get a new bug fix release out soon with these changes but trying to get #335 settled and merged first.

**Comment by BadCo-NZ** [comment]
> I just pushed some commits related to #346 that may relate to this issue as well. Appreciate if folks who are able to run an instance from `master` can give their issues from this thread a test again. I also hope to get a new bug fix release out soon with these changes but trying to get #335 settled and merged first.

Thanks @cdubz, I'll have a go at spinning it up later tonight

**Comment by JoeArcher007** [comment]
Here's the experience that I'm having with this issue (hopefully not cluttering this issue):

Timezone is America/Toronto
Using Build v1.9.1-ls18 in Docker on Ubuntu 21.10 x64 Virtual Machine

If I do a reboot of the physical server host, or the vm hosting the docker instance, it doesn't work correctly. If I restart the Docker container after the reboot, it works again. Not sure exactly how that is resolving it, but that's been my workaround lately. I haven't done any reverting and can now add entries without the issue popping up.

**Comment by cdubz** [comment]
@JoeArcher007 just to be clear, when you say "it" works and doesn't work -- you mean the frontend datetime validation on fields? Assuming so, definitely not clogging up the issue (:

**Comment by JoeArcher007** [comment]
Good call, I should have been more clear there 👍🏻. And yes, the "It" being that when using a quick timer and entering that quick timer as a sleep/tt/eating entry, it auto-populates the date/time fields correctly and also validates correctly as well. Thank you!

**Comment by cdubz** [comment]
Hi folks 👋 I was trying to wait out a couple of other issues but this one seems like a PITA and it _may_ be fixed by some other changes so I released a [v1.9.2](https://github.com/babybuddy/babybuddy/releases/tag/v1.9.2) with those changes. For those having this issue please give it a try and let us know if you still have issues. Thanks!

**Comment by meeb** [comment]
Hi @cdubz - unfortunately `v1.9.2` has not fixed this for us, we still get the "Enter a valid date/time" error regardless of the date format used. I've rolled back to `v1.9.0-ls14` again which fixes it for the moment. Cheers.

**Comment by cdubz** [comment]
Thanks for testing! Too bad it didn’t magically fix itself… it’ll be another few weeks before I can really test this. Is anyone here able to reproduce outside of Docker? I think so far everyone reporting this is using Docker?

**Comment by Borlean** [comment]
Yes, I'm using via Docker.

**Comment by cdubz** [comment]
Additional question -- is anyone here getting this issue when first starting to use Baby Buddy or just after upgrading from some version before v1.9.1? I finally had some time today to test using the Composer config @BadCo-NZ provided but I couldn't seem to to find a way to replicate the issue.

Also for those experiencing this issue when upgrading -- could you test starting up a _new_ instance from the latest version with the same settings? I'm curious if there is a simple browser caching issue here between the updates, though @BadCo-NZ did say they cleared browser caching when first troubleshooting...

**Comment by BadCo-NZ** [comment]
> Thanks for testing! Too bad it didn’t magically fix itself… it’ll be another few weeks before I can really test this. Is anyone here able to reproduce outside of Docker? I think so far everyone reporting this is using Docker?

Originally I did try to run it in a LXC container, but I couldn't get it working. If you want to walk me through it I will be happy to try again?

> Additional question -- is anyone here getting this issue when first starting to use Baby Buddy or just after upgrading from some version before v1.9.1? I finally had some time today to test using the Composer config @BadCo-NZ provided but I couldn't seem to to find a way to replicate the issue.
> 
> Also for those experiencing this issue when upgrading -- could you test starting up a _new_ instance from the latest version with the same settings? I'm curious if there is a simple browser caching issue here between the updates, though @BadCo-NZ did say they cleared browser caching when first troubleshooting...

I have a test instance of BabyBuddy on a different "host" that I need to test this issue with. It is on the to-do list!

**Comment by cdubz** [comment]
I don’t even know what an LXC container is 😁 Was curious if anyone ran in to this with the “manual” install method but I guess Docker is what a majority of users use…

Thanks in advance for testing. A user on Gitter is able to reproduce with a fresh instance so it does seem to be more than just something about updating.

**Comment by BadCo-NZ** [comment]
> I don’t even know what an LXC container is grin Was curious if anyone ran in to this with the “manual” install method but I guess Docker is what a majority of users use…
> 
> Thanks in advance for testing. A user on Gitter is able to reproduce with a fresh instance so it does seem to be more than just something about updating.

LXC is basically a system container vs Docker being an application container. It is an OS that shares the kernel with the host, so in essence it would be a "manual install"

**Comment by BadCo-NZ** [comment]
Ok a quick test while the baby is screaming for his bottle haha

New install (ver 1.9.2) with the below compose, I get the same issue with my local timezone set (I can't even start a timer).

However, if I set the timezone to UTC (under user settings) I am able to start a timer and save it.

```
version: "2.1"
services:
  app:
    image: lscr.io/linuxserver/babybuddy
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - config:/config
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.10.11.166
    dns:
      - 10.10.11.1
      
networks:
  default:
    external:
      name: public
      
volumes:
  config:
```

**Comment by cdubz** [comment]
Thanks for confirming. Feed that baby!

🕵️‍♂️

**Comment by lelandbay** [comment]
I was having the same issue with not being able to enter activities because if an invalid date / time.

My time zone was America / New York and the language is English (US).

I tried changing the language to English (UK) and it allowed me to enter activities. But after I changed the language all my activities I had before that shifted back to activities in May. Like a 12/6 date became 5/6.

I changed the language back to English (US) and tested and it shifted the activities back to the correct times. I was then again unable to add activities.

I changed the time zone to America / Detroit and now everything works fine.

Hopefully these details help.

**Comment by kdrobnyh** [comment]
Had the same issue when tried to migrate from 1.9.0 to 1.9.1. Did not use Docker, Babybuddy was installed in my system to use with MariaDB. Time zone is America/Phoenix and the language is English (US). Tried to find the issue using git-bisect, but was not able to reproduce the issue even with 1.9.1. Was in a hurry to fix that, so might have missed something.

**Comment by cdubz** [comment]
Thanks, @kdrobnyh -- good to hear from someone _not_ using Docker to further confirm this is an issue with the app itself. I'm not 99% sure this stems from https://github.com/babybuddy/babybuddy/commit/d74f35d765a6e90b06e893219b237959406685cf. I made this change to support proper default date formatting for the en-GB language because Django's default settings are weird. I'm trying to avoid reverting this entirely and have https://github.com/babybuddy/babybuddy/pull/335 that _may_ have an affect but I was hoping to get some more feedback on it. Also, annoyingly, I still cannot seem to reproduce this in any environment. I think I'm just going to go ahead and merge https://github.com/babybuddy/babybuddy/pull/335 soon...

**Comment by kdrobnyh** [comment]
I have some updates about the issue: we have 2 BabyBuddy users. Today I switched to Docker and updated BabyBuddy to 1.9.2. I checked from my phone - everything seemed to work as usual. However, when my wife tried to add a new entry, she encountered this error (Enter a valid date/time.). POST messages were identical from both users, but one received error, the other did not. I checked the database - for one user the language was "en-US" (no errors), for another one is "en" (the error mentioned above). In GUI settings (on the website), both users have chosen language "English (US)". I believe that caused the issue, since when I changed the language, everything started to work again. That also supports @lelandbay 's comment above.

**Comment by cdubz** [comment]
@kdrobnyh thanks for digging! That actually makes sense and may explain this issue completely... I did not consider the fact that changing the server default from `en` to `en-US` would require a migration but I bet it _does_ for users who had previously access and saved the settings form (giving themselves a setting of `en` before the update). This may be the key to this whole debacle... I'll take a look later today.

**Comment by cdubz** [comment]
Ok all, I think I have this resolved on `master` -- would appreciate if someone here is able to test and confirm but regardless I'll create a new release in the next 24 hours or so. Big thanks to @kdrobnyh for the sleuthing that led me to be able to reproduce and fix this.

**Comment by BadCo-NZ** [comment]
Just checked on a test instance, seems to be working without errors. I will try and migrate my DB tonight (story for another time) and test in production and report back.

Thanks @cdubz, @kdrobnyh and everyone else who commented on the issue.
